name: Editorconfig-Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  editorconfig-checker:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v6.0.0

    - name: Get editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@v2

    - name: Run editorconfig-checker
      run: editorconfig-checker
