name: Editorconfig-Checker
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  editorconfig-checker:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v6.0.2

    - name: Get editorconfig-checker
      uses: editorconfig-checker/action-editorconfig-checker@v2

    - name: Run editorconfig-checker
      run: editorconfig-checker
